version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/fadi12321/test-for-deep-11"