---
- name: Install client SSH pubkey
  authorized_key:
    user: root
    key: "{{ hostvars[groups['client'][0]]['client_ssh_key'] | b64decode }}"

# needed for Ansible > 4.0 https://github.com/ansible/ansible/issues/74830
- name: Install acl
  apt:
    name:
      - acl
    state: present

# Set high uid to ensure it's not squashed by another service
- name: Create 'git' user
  user:
    name: git
    uid: 1999
    groups: admin,google-sudoers
    append: true

- name: Mount repositories disk
  mount:
    path: /mnt/git-repositories
    src: /dev/disk/by-id/google-repository-disk
    fstype: ext4
    opts: discard,defaults
    state: mounted

- name: Set git as owner of git-repositories directory
  file:
    path: /mnt/git-repositories
    owner: git
    group: git
    state: directory
    recurse: yes

- name: Create /src directory
  file:
    path: /src
    state: directory
    mode: '0755'
    owner: git
    group: git

# Match limits set by Omnibus
- name: Set file-max
  shell: echo "1000000" > /proc/sys/fs/file-max

- name: Update apt cache
  apt: update_cache=yes
