---
- name: Set user-defined variables
  hosts: localhost
  connection: local
  vars_prompt:
    - name: gitaly_revision
      prompt: "Enter Gitaly revision to build"
      default: HEAD
      private: false

    - name: gitaly_benchmarking_instance_name
      prompt: "Enter a name for your benchmark instance"
      default: "{{ lookup('env', 'USER') }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}"
      private: false

    - name: ssh_pubkey
      prompt: "Enter the path to your SSH public key"
      default: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
      private: false
  roles:
    - deploy
  gather_facts: false
