---
- name: Set run_name
  set_fact: "run_name=benchmark-{{ gitaly_revision }}-{{ lookup('pipe', 'date +%s') }}"

- name: Run benchmarks
  vars:
    profile: true
    clear_page_cache: true
  include_tasks: rpc_loop.yml
  loop: "{{ rpcs }}"
  loop_control:
    loop_var: rpc_info

- name: Archive results
  archive:
    path:
    - "/tmp/{{ run_name }}"
    dest: "/tmp/{{ run_name }}.tar.gz"
    owner: git

- name: Fetch results
  fetch:
    src: "/tmp/{{ run_name }}.tar.gz"
    dest: "{{ playbook_dir }}/results/"
    flat: true
